import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Label } from '@/components/ui/label';
import { ShieldCheck, UserPlus } from 'lucide-react';
import { toast } from 'sonner';
import { Link } from 'react-router-dom';
import LanguageSwitcher from '@/components/shared/LanguageSwitcher';

const registrationSchema = z.object({
  name: z.string().min(2, 'Name is required').max(100),
  shopName: z.string().min(2, 'Shop name is required').max(100),
  phone: z.string().min(10, 'Valid phone required').max(15),
  address: z.string().min(5, 'Address is required').max(300),
  nid: z.string().max(20).optional(),
  password: z.string().min(6, 'Min 6 characters').optional().or(z.literal('')),
  applyAsMember: z.boolean().default(true),
});

type RegistrationData = z.infer<typeof registrationSchema>;

export default function PublicRegistrationPage() {
  const { t } = useTranslation();

  const form = useForm<RegistrationData>({
    resolver: zodResolver(registrationSchema),
    defaultValues: { name: '', shopName: '', phone: '', address: '', nid: '', password: '', applyAsMember: true },
  });

  const handleSubmit = (_data: RegistrationData) => {
    toast.success(t('memberRequests.applicationSubmitted'));
    form.reset();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-muted/30 flex items-center justify-center p-4">
      <Card className="w-full max-w-lg">
        <CardHeader className="text-center">
          <div className="flex items-center justify-center gap-2 mb-2">
            <ShieldCheck className="h-8 w-8 text-primary" />
            <h1 className="font-heading text-2xl font-bold">Somitee<span className="text-primary">HQ</span></h1>
          </div>
          <CardTitle className="font-heading text-xl">{t('memberRequests.publicFormTitle')}</CardTitle>
          <CardDescription>{t('memberRequests.publicFormSubtitle')}</CardDescription>
          <div className="flex justify-center mt-2"><LanguageSwitcher /></div>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <FormField control={form.control} name="name" render={({ field }) => (
                  <FormItem><FormLabel>{t('common.name')} *</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="shopName" render={({ field }) => (
                  <FormItem><FormLabel>{t('members.shopName')} *</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <FormField control={form.control} name="phone" render={({ field }) => (
                  <FormItem><FormLabel>{t('common.phone')} *</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="nid" render={({ field }) => (
                  <FormItem><FormLabel>{t('members.nid')} ({t('members.optional')})</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
              </div>
              <FormField control={form.control} name="address" render={({ field }) => (
                <FormItem><FormLabel>{t('common.address')} *</FormLabel><FormControl><Textarea {...field} rows={2} /></FormControl><FormMessage /></FormItem>
              )} />
              <div className="space-y-1">
                <Label>{t('members.profileImage')}</Label>
                <Input type="file" accept="image/*" />
                <p className="text-xs text-muted-foreground">{t('members.optional')}</p>
              </div>
              <FormField control={form.control} name="password" render={({ field }) => (
                <FormItem><FormLabel>{t('common.password')} ({t('members.optional')})</FormLabel><FormControl><Input type="password" placeholder={t('members.autoGenerated')} {...field} /></FormControl><FormMessage /></FormItem>
              )} />
              <FormField control={form.control} name="applyAsMember" render={({ field }) => (
                <FormItem className="flex items-center gap-2 space-y-0">
                  <FormControl><Checkbox checked={field.value} onCheckedChange={field.onChange} /></FormControl>
                  <FormLabel className="cursor-pointer">{t('memberRequests.applyAsMember')}</FormLabel>
                </FormItem>
              )} />
              <Button type="submit" className="w-full"><UserPlus className="h-4 w-4 mr-2" /> {t('memberRequests.submitApplication')}</Button>
              <p className="text-center text-sm text-muted-foreground">
                {t('auth.hasAccount')} <Link to="/login" className="text-primary hover:underline">{t('auth.login')}</Link>
              </p>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
}
